### ISSUE TITLE
[Bug] Cascades persist after chunk unloading

### ISSUE THREAD

**Issue by xXNickznXx** [Chailotl/particular#12]
The cascades persist even after chunk unloading.
It gets obvious when using your mod in combination with a mod that removes the vanilla fog, for example [No Fog](https://modrinth.com/mod/no_fog) or [Distant Horizons](https://modrinth.com/mod/distanthorizons)
No Fog:
![2024-05-25_01 28 54](https://github.com/Chailotl/particular/assets/31235664/e6460979-d007-4096-8ea5-0704c3791f39)
Distant Horizons:
![2024-05-25_01 34 44](https://github.com/Chailotl/particular/assets/31235664/620526fa-400d-4631-892a-46e3477870af)

**Comment by Chailotl** [comment]
Uh oh, I guess the code I wrote specifically for this isn't working, thanks for reporting this.

Unfortunately I won't be able to fix this issue for the next week as I'll be on vacation ^^;

**Comment by xXNickznXx** [comment]
No stress and a nice vacation :D

**Comment by Chailotl** [comment]
I've identified and fixed the issue 👍
