### ISSUE TITLE
[SUGGESTION] Option to have leaf particles not stick to the ground, or at least stick in a axis-alligned manner.

### ISSUE THREAD

**Issue by acki02** [Chailotl/particular#13]
As the title says, I think it would be neat if the mod had an option to either:
a) let the fallen leaves not snap to ground/water like they do in the Falling Leaves mod; or
b) have them allign themselves to the world X and Z axes (though not necessairly to the pixel grid, for better visibility), with a slight upward offset on Y axis (again, for better visibility).

It would be doubly great if both options were to be implemented.

**Comment by Chailotl** [comment]
By "snapping to the ground", do you mean how they lay flat on the ground? If so, I could make this configurable ^^

Could you elaborate the second part though, please?

**Comment by acki02** [comment]
Yes, this is indeed what I had in mind.

As for this second part, what I had in mind was an option for the flat-lying leaves to allgin themselves into right angles compared to the coordinate grid (though not strictly to the pixel grid), and also to get a little offset from the ground, akin to what Glow Lichen has.

**Comment by Chailotl** [comment]
Both of these options will be available in the next update, though I opted to skip the y offset
