### ISSUE TITLE
[suggestion] Add splash effect for fishing rod

### ISSUE THREAD

**Issue by CanecaKun** [Chailotl/particular#19]
The fishing rod entity does not create a splash when falling into water, and does not make a splash when a fish bites it, i think an effect there would be great,

Also is there sound for the waterfalls? IDK if its a config on my side or if its muted by default

**Comment by Chailotl** [comment]
This was fixed with #18

There currently isn't any waterfall sounds but I'm working on it, I just have quite a bit on my plate

**Comment by CanecaKun** [comment]
Oh cool, thank you for your hard work!
