### ISSUE TITLE
Game won't launch with 1.1.0

### ISSUE THREAD

**Issue by kristiannotari** [Chailotl/particular#21]
Hey, just wanted you to know I was playing with 1.0.4 with no problems and when I tried 1.1.0 game won't launch.

I'm on 1.20.1 fabric 0.15.11, with 159 other mods. I do have regions unexplored and wilder wild, but I don't have traverse.

Here's the crash log. Hope it helps!
[particular-crash-1-0-0.txt](https://github.com/user-attachments/files/15751151/particular-crash-1-0-0.txt)

**Comment by Chailotl** [comment]
It looks like Wilder Wild changed something from 1.20 (the base version I dev for) to 1.20.1 that's breaking the falling leaves compat, so I'll need to figure out something more robust

**Comment by vague2k** [comment]
Same issue for me btw, i'll be following the issue incase of updates

**Comment by Chailotl** [comment]
Fixed in Particular 1.1.1 and specifically tested on 1.20.1 with Wilder Wilds
