### ISSUE TITLE
[BUG] Steam clouds in seemingly random locations in the end

### ISSUE THREAD

**Issue by atLancelot** [Chailotl/particular#3]
The overworld was fine as far as I could tell, but when I travelled to the end, I was greeted with this.
![2024-05-18_12 17 35](https://github.com/Chailotl/particular/assets/56614578/cbae2e6d-7fb1-4ec6-9eed-f0d85128b362)
This was on Fabric, 1.20.4 Version 1.0.0 (Mentioning in case of an update)

**Comment by Chailotl** [comment]
God, I know what the issue is xD

I forgot to clear active cascades when changing dimensions, the same exact bug used to happened when changing world, I'll have it fixed asap
