### ISSUE TITLE
1.21 port please

### ISSUE THREAD

**Issue by thesh1xx** [Chailotl/particular#34]
i really need this mod for my modpack on 1.21

**Comment by Carmabound** [comment]
Same

**Comment by DracoFrostDragon** [comment]
^^^

**Comment by PixelTails** [comment]
Please, i need it

**Comment by pobblebonkq** [comment]
Such an aesthetic, would be awesome on 1.21

**Comment by pvpincarnate** [comment]
There is a PR for a 1.21 port. You just have to compile it yourself. [https://github.com/Chailotl/particular/pull/37](url)

**Comment by Chailotl** [comment]
There is a jank 1.21 port now, a properly supported port will come later when I finish the major features for 1.20
