### ISSUE TITLE
[Crash] Mods Incompatibilities

### ISSUE THREAD

**Issue by SebSemos** [Chailotl/particular#4]
Hi, got crashes with three of my mods. Got the feeling they're the same issue but here is the 3 crash reports. (I play on 1.20.1)

Mods are [MoreCarpets](https://modrinth.com/mod/blackwolf-more-carpets), [Smooth Particules](https://modrinth.com/mod/smooth-particles) and [Fancy Block Particules](https://modrinth.com/mod/fbp-renewed)

[MoreCarpets.txt](https://github.com/Chailotl/particular/files/15367106/MoreCarpets.txt)
[smoothparticles.txt](https://github.com/Chailotl/particular/files/15367107/smoothparticles.txt)
[FancyBlockParticles.txt](https://github.com/Chailotl/particular/files/15367109/FancyBlockParticles.txt)

**Comment by Chailotl** [comment]
At first glance the first two mods seem to have errors completely unrelated to Particular, but I assume they work fine if Particular is disabled so I'll have to do some investigating. The last mod conflict is due to a bit of an invasive mixin on my end. I can try my best to rework it so that it is compatible with Fancy Block Particles.

**Comment by SebSemos** [comment]
Yep, all these mods works fine without Particular, and each crash logs provided is with only the said mod + particular

**Comment by pajicadvance** [comment]
The only real incompatibility issue here is between Particular and Fancy Block Particles. Smooth Particles crashes because you don't have MidnightLib installed, and More Carpets crashed because you don't have Blackwolf Library installed.

**Comment by SebSemos** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️ Let's pretend I was tired 😂
In my defence usually when a lib is missing I got a withe screen telling me so. Not here :p 
It work indeed fine with libs.
Funny I had not MidnightLib at all, must be embedded in another mod.
