### ISSUE TITLE
Compat/Features add (water splash and bubbles effects)

### ISSUE THREAD

**Issue by IntMarco** [Chailotl/particular#9]
There're
https://modrinth.com/mod/wakes
https://modrinth.com/mod/make_bubbles_pop

Or you could add some features from these mods.

**Comment by Chailotl** [comment]
If you mean disabling Particular's effects, you can already toggle off any individual effect through the config

**Comment by IntMarco** [comment]
- Yes I know, it would be useful to make the config automatic just for beginner users.
- Do you ever add features like those in the mods mentioned above, especially like the Make Bubble Pop ones?

**Comment by Torathion** [comment]
On the bottom of the mod description, popping bubbles are already mentioned. I also would like a wakes features as I mentioned it in #2

**Comment by IntMarco** [comment]
Yup, I was talking about trident trials and underwater explosion, anyway ty for the reply
